version: "3.8"

volumes:
  postgres-database:
    driver: local

services:
  toggl-cards:
    build: .
    container_name: toggl-cards
    ports:
      - "8080:8080"
    environment:
      PORT: ":8080"
      DB_HOST: postgres
      DB_USER: toggl
      DB_PASSWORD: toggl
      DB_NAME: cards
    depends_on:
      - postgres
    restart:
      always

  postgres:
    container_name: toggl-postgres
    ports:
      - "5432:5432"
    build:
      context: postgres
      dockerfile: $PWD/postgres/Dockerfile
    environment:
      POSTGRES_DB: toggl
      POSTGRES_USER: toggl
      POSTGRES_PASSWORD: toggl
    volumes:
      - postgres-database:/var/lib/postgresql/data
